apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrosolutions-azurefunction-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrosolutions-azurefunction-functions
  template:
    metadata:
      labels:
        app: agrosolutions-azurefunction-functions
    spec:
      containers:
        - name: agrosolutions-azurefunction-functions
          image: marioguilhermedev/agrosolutions-azurefunction:latest
          ports:
            - containerPort: 80
          env:
            - name: RabbitMQConnection
              valueFrom:
                configMapKeyRef:
                  name: agrosolutions-azurefunction-config
                  key: RabbitMQConnection

            - name: AzureWebJobsStorage
              value: "DefaultEndpointsProtocol=https;AccountName=teste343454352345;AccountKey=UTp6KJsIHFisLZphkQtqUNf2Kr9HFtyB7qbJ4E+zjBSu/Yg5NiQfyIEOnZc+OmBXE/BR6E7BphyN+AStkOmwRg==;EndpointSuffix=core.windows.net"

          envFrom:
          - configMapRef:
              name: agrosolutions-azurefunction-config
          - secretRef:
              name: agrosolutions-azurefunction-secret
