apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrosolutions-azurefunctions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agrosolutions-azurefunctions
  template:
    metadata:
      labels:
        app: agrosolutions-azurefunctions
    spec:
      containers:
        - name: agrosolutions-azurefunctions
          image: marioguilhermedev/agrosolutions-azurefunctions:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: agrosolutions-azurefunctions
spec:
  type: NodePort
  selector:
    app: agrosolutions-azurefunctions
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080